### ISSUE TITLE
Debian / Extended support

### ISSUE THREAD

**Issue by AurelienDuval6** [JonasGroeger/jetbrains-ppa#30]
Could you also add support for debian(stable, testing and unstable) please ? :smiley:

However, you might prefer to create / add a single "common" repository in your case as you upload the same .deb file for each distribution. 
This way, you would not have to manually add new versions of Ubuntu / Debian.
In the long term, you will just have to remove End of Life Ubuntu / Debian versions.

Thanks !

**Comment by JonasGroeger** [comment]
How exactly does this "common" repository work?

**Comment by gregorydk** [comment]
@JonasGroeger  OP probably means giving the repo directory a common name like 'default' or 'any' instead of the distro's code name (currently hirsute). That way the name is generic and fits also Debian and you can just upload the package into that directory, instead of maintaining multiple directories.

**Comment by JonasGroeger** [comment]
Hey @gregorydk and @AurelienDuval6 

I created a draft in https://github.com/JonasGroeger/jetbrains-ppa/pull/45 Is this what you meant?

**Comment by gregorydk** [comment]
@JonasGroeger Yes, this is it what @AurelienDuval6 (I think) and I meant. :-)

**Comment by jorkanofaln** [comment]
Is supports Debian 11 Bullseye if focal is used as the selected distro for this repo, for more info: https://wiki.debian.org/JetBrains
