### ISSUE TITLE
Question: Apt shows that it'll free essentially no space on IDE's removal

### ISSUE THREAD

**Issue by ajitid** [JonasGroeger/jetbrains-ppa#69]
(I think it really won't matter which package I'm going to remove here, but) When I remove GoLand I see only few KBs to be freed.

![Screenshot from 2024-01-21 16-01-11](https://github.com/JonasGroeger/jetbrains-ppa/assets/26769888/079533e0-9db0-4cb1-b066-74d8304d362e)

Running autoremove doesn't frees any space either. I don't know where exactly to look for to verify if GoLand has been properly removed. Could you help me out here please?

**Comment by JonasGroeger** [comment]
The calculated freed disk space is based on the package contents. Due to licensing issues (we don't own the IDE packages) we have to download them in a separate post installation script which does not add to the shown freed space.

You can check the installation directory if it was removed. Should be under `/opt/goland`. Should be non-existent after removal due to https://github.com/JonasGroeger/jetbrains-ppa/blob/master/packages/goland/postremove

**Comment by ajitid** [comment]
Yes, the dir doesn't exist. I wasn't aware about how apt accounts for size, thank you.
